apiVersion: v1
kind: Service
metadata:
  name: analyzer-translator
spec:
  type: NodePort
  selector:
    app: analyzer-translator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

